# Numpy 

In [43]:
import numpy as np

<h2>Introduction to numpy arrays</h2>

In [44]:
k=np.array([1,2,3,4])

In [45]:
k

array([1, 2, 3, 4])

it is a numpy array

In [46]:
type(k)

numpy.ndarray

it is of type ndarray

<h3>types of numpy arrays </h3>

<b>1d array</b>

In [47]:
a=np.array([1,2,3,4])

In [48]:
a

array([1, 2, 3, 4])

In [49]:
np.shape(a)

(4,)

<b>2d array 

In [50]:
b=np.array([[1,2,3,4],[1,2,3,4]])

In [51]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [52]:
np.shape(b)

(2, 4)

<b>3d array

In [53]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [54]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
np.shape(c)

(2, 2, 2)

<b> numpy array from  python list

In [56]:
list=[1,2,3,4,5]

In [57]:
d=np.array(list)

In [58]:
d

array([1, 2, 3, 4, 5])